version: '3.8'
services:
  db:
    image: neutrl/shopify-postgres-dev:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/data/postgres
    restart: unless-stopped
    networks:
      - postgres
  pgadmin:
    image: neutrl/shopify-pgadmin-dev:latest
    container_name: pgadmin_container
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=developer

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: